r92su: fix checkpatch.pl complains
This patch fixes almost all complains from checkpatch.
What is left unfixed:

1.

ERROR: Macros with complex values should be enclosed in parenthesis
+#define TRACE_INCLUDE_PATH .

Reason:
	TRACE_INCLUDE_PATH content will be part of a include <...> path,
	so it can't be placed into ().

2.

WARNING: Avoid CamelCase: <intf->cur_altsetting->desc.bNumEndpoints>
+       r92su->ep_num = intf->cur_altsetting->desc.bNumEndpoints;

Reason:
	bNumEndpoints is part the official name from the usb spec.

Signed-off-by: Christian Lamparter <chunkeey@googlemail.com>